### ISSUE TITLE
Problem with self-signed cert on smtp-server.

### ISSUE THREAD

**Issue by joberget** [dangmai/hetzner-notifier#1]
Hi dangmai, thanks for a nice application.

I had to turn this setting on when using SSL-cert on the mail server since I use a self-signed SSL-cert on my smtp.

process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0" // Avoids DEPTH_ZERO_SELF_SIGNED_CERT error for self-signed certs

Otherwise the server will throw the following:

Error sending email notification: Error: DEPTH_ZERO_SELF_SIGNED_CERT

I found the issue here: https://github.com/request/request/issues/418

**Comment by dangmai** [comment]
I'm glad you find the library to be useful, @joberget, and thanks for the bug report.

I'm using nodemailer to send email here, and it seems that they have an option to override the default behavior that you're using. Unfortunately I don't have a self-signed SMTP server to test with right now, do you mind helping me with it? If you can, try (after removing the `process.env` workaround you put in earlier) changing the option https://github.com/dangmai/hetzner-notifier/blob/master/index.js#L39 to:

```
var transporter = nodemailer.createTransport({
    host: config.smtp_host,
    port: config.smtp_port,
    auth: {
        user: config.smtp_username,
        pass: config.smtp_password
    },
    tls: {
        rejectUnauthorized: true
    }
});
```

If that works I can add an option to the program to enable this behavior. Thanks!

**Comment by joberget** [comment]
I will try this out tomorrow and report back, thanks!

**Comment by joberget** [comment]
Tested it now. And I got the same error for rejectUnauthorized: true and changing it to false worked just fine.

``` node
var transporter = nodemailer.createTransport({
    host: config.smtp_host,
    port: config.smtp_port,
    auth: {
        user: config.smtp_username,
        pass: config.smtp_password
    },
    tls: {
        rejectUnauthorized: false
    }
});
```

**Comment by dangmai** [comment]
Okay, I've added the option `--smtp_accept_unauthorized` to the program in 901a0bdc. Can you try it out and let me know if it works? The options is described in the README file as well. Thanks for your help!

**Comment by joberget** [comment]
Works!

```
hetzner-notifier/ (master✗) $ node index.js 
Error sending email notification: Error: DEPTH_ZERO_SELF_SIGNED_CERT
hetzner-notifier/ (master✗) $ node index.js --smtp_accept_unauthorized                            
Email notification sent: 250 2.0.0 Ok: queued as 900671FFC6
```

**Comment by dangmai** [comment]
Awesome, thanks for the bug report!
